version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=aaron 
      - POSTGRES_DB=secrets
    ports:
      - "5432:5432"
    depends_on:
      - translation

  translation:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  API:
    image: secscrape_api
    expose:
      - "80"
    ports:
      - "80:80"

  scraper:
    image: webscraper_secret
    environment:
      - PAGES=1
      - LANGS_CS=de,en,es,fr,vi
      - PYTHONUNBUFFERED=1
    depends_on:
      - translation
      - database


